### ISSUE TITLE
empty kleeja-master.zip file in cashe folder

### ISSUE THREAD

**Issue by MitanOmar** [MitanOmar/plugins_updater#2]

**Comment by MitanOmar** [comment]
@abdumu thank you bro ,
i dont know maybe the problem is from my host  ,
but the zip file is empty :(

**Comment by abdumu** [comment]
Try it on Kleeja master repo.

**Comment by abdumu** [comment]
هل جربتها على كليجا التي لم تصدر وواجهت المشكلة ذاتها ؟

**Comment by MitanOmar** [comment]
للاسف لم اجربها بعد . انا اعمل الان على اضافة kj_paypal
ولكن ساجربها اليوم وارد لك النتيجة

**Comment by abdumu** [comment]
👍🏼

**Comment by MitanOmar** [comment]
تم حل المشكلة . شكرا
